#!/bin/sh

cd ~/gist/snippets
snippets build

# Table
snippets show                         > show.txt
snippets get all                 | jq > get-all.json
snippets get snippets crystal    | jq > get-snippets-crystal.json
snippets get snippet crystal def | jq > get-snippet-crystal-def.json
snippets get input_paths         | jq > get-input-paths.json
snippets get output_path         | jq > get-output-path.json
snippets get files               | jq > get-files.json

git add .
commit_message=$(date '+%F %T')
git commit --message="$commit_message"
git push

# Open gist
chromium https://gist.github.com/alexherbo2/d6351c92996d0ce2ead82cb35a91250f
